---
    - name: Run a shell command and register its output as a variable
      ansible.builtin.shell: "/bin/bash cat /proc/sys/kernel/hostname"
      register: actual_hostname
      ignore_errors: true

    - name: set hostname if not set.
      become_user: root
      shell: hostnamectl set-hostname "{{HostName}}"
      when: actual_hostname != '{{HostName}}'

    - name: set pretty if hostname was not set.
      become_user: root
      shell: hostnamectl set-hostname "{{HostName}}" --pretty
      when: actual_hostname != '{{HostName}}'